TessierAshpool.WinStreakers.Web/Areas/Admin/Controllers/MatchesController.cs
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using TessierAshpool.WinStreakers.Business.Entities;
using TessierAshpool.WinStreakers.DataAccess.Utilities;

// <author>Jonas Benzon Illum</author>

namespace TessierAshpool.WinStreakers.Web.Areas.Admin.Controllers
{
    public class MatchesController : Controller
    {
        private WinStreakersDbContext db = new WinStreakersDbContext();

        // GET: Admin/Matches
        public ActionResult Index()
        {
            var matches = db.Matches.Include(m => m.Game).Include(m => m.Tournament);
            return View(matches.ToList());
        }

        // GET: Admin/Matches/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Match match = db.Matches.Find(id);
            if (match == null)
            {
                return HttpNotFound();
            }
            return View(match);
        }

        // GET: Admin/Matches/Create
        public ActionResult Create()
        {
            ViewBag.GameId = new SelectList(db.Games, "GameId", "Name");
            ViewBag.TournamentId = new SelectList(db.Tournaments, "TournamentId", "Name");
            return View();
        }

        // POST: Admin/Matches/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "MatchId,Description,StartTime,GameId,TournamentId")] Match match)
        {
            if (ModelState.IsValid)
            {
                db.Matches.Add(match);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.GameId = new SelectList(db.Games, "GameId", "Name", match.GameId);
            ViewBag.TournamentId = new SelectList(db.Tournaments, "TournamentId", "Name", match.TournamentId);
            return View(match);
        }

        // GET: Admin/Matches/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Match match = db.Matches.Find(id);
            if (match == null)
            {
                return HttpNotFound();
            }
            ViewBag.GameId = new SelectList(db.Games, "GameId", "Name", match.GameId);
            ViewBag.TournamentId = new SelectList(db.Tournaments, "TournamentId", "Name", match.TournamentId);
            return View(match);
        }

        // POST: Admin/Matches/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "MatchId,Description,StartTime,GameId,TournamentId")] Match match)
        {
            if (ModelState.IsValid)
            {
                db.Entry(match).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.GameId = new SelectList(db.Games, "GameId", "Name", match.GameId);
            ViewBag.TournamentId = new SelectList(db.Tournaments, "TournamentId", "Name", match.TournamentId);
            return View(match);
        }

        // GET: Admin/Matches/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Match match = db.Matches.Find(id);
            if (match == null)
            {
                return HttpNotFound();
            }
            return View(match);
        }

        // POST: Admin/Matches/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Match match = db.Matches.Find(id);
            db.Matches.Remove(match);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

TessierAshpool.WinStreakers.Web/Areas/User/Controllers/GameController.cs
using System.Linq;
using System.Web.Mvc;
using TessierAshpool.WinStreakers.DataAccess.Repositories.Interfaces;

// <author>Jonas Benzon Illum</author>

namespace TessierAshpool.WinStreakers.Web.Areas.User.Controllers
{
    public class GameController : Controller
    {

        private IGameRepository _gameRepository;

        public GameController(IGameRepository gameRepository)
        {
            _gameRepository = gameRepository;
        }

        public ViewResult ShowGame(int id = 1)
        {
            return View(_gameRepository.FindById(id));
        }

        public ViewResult ListGames()
        {
            return View(_gameRepository.Games.OrderBy(game => game.Name));
        }

    }
}

TessierAshpool.WinStreakers.Web/Areas/User/Controllers/MatchController.cs
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using TessierAshpool.WinStreakers.Business.Entities;
using TessierAshpool.WinStreakers.DataAccess.Repositories.Interfaces;
using TessierAshpool.WinStreakers.Web.Areas.User.ViewModels;

// <author>Jonas Benzon Illum</author>

namespace TessierAshpool.WinStreakers.Web.Areas.User.Controllers
{
    public class MatchController : Controller
    {

        private IMatchRepository _matchRepository;
        private ITeamsAndOddsRepository _teamsAndOddsRepository;

        public MatchController(IMatchRepository matchRepository, ITeamsAndOddsRepository teamsAndOddsRepository)
        {
            _matchRepository = matchRepository;
            _teamsAndOddsRepository = teamsAndOddsRepository;
        }

        public PartialViewResult ShowMatch(int id)
        {
            MatchAndTeamViewModel matchAndTeamVM = MatchAndTeamViewModel(_matchRepository.FindById(id));
            return PartialView(matchAndTeamVM);
        }

        public ActionResult ShowWithMatch(Match match)
        {
            MatchAndTeamViewModel matchAndTeamVM = MatchAndTeamViewModel(match);
            return View("ShowMatch", matchAndTeamVM);
        }

        public PartialViewResult ListMatches(Game game)
        {
            List<MatchInListViewModel> matchesInList = game.Matches.Select(match => new MatchInListViewModel
            {
                MatchId = match.MatchId,
                GameName = game.Name,
                StartTime = match.StartTime,
                TeamOneName = match.TeamsAndOddsForMatches.First().Team.Name,
                TeamOneOdds = match.TeamsAndOddsForMatches.First().Odds,
                TeamTwoName = match.TeamsAndOddsForMatches.Last().Team.Name,
                TeamTwoOdds = match.TeamsAndOddsForMatches.Last().Odds,
                DrawOdds = (match.TeamsAndOddsForMatches.First().Odds 
                            + match.TeamsAndOddsForMatches.Last().Odds) * 0.15
            }).ToList();
            return PartialView(matchesInList);
        }
        public ViewResult ListAllMatches()
        {
            return View("ListMatches", _matchRepository.Matches.Select(match => new MatchInListViewModel
            {
                MatchId = match.MatchId,
                StartTime = match.StartTime,
                TeamOneName = match.TeamsAndOddsForMatches.First().Team.Name,
                TeamOneOdds = match.TeamsAndOddsForMatches.First().Odds,
                TeamTwoName = match.TeamsAndOddsForMatches.Last().Team.Name,
                TeamTwoOdds = match.TeamsAndOddsForMatches.Last().Odds,
                DrawOdds = (match.TeamsAndOddsForMatches.First().Odds 
                            + match.TeamsAndOddsForMatches.Last().Odds) * 0.15
            }).ToList());
        }

        public PartialViewResult MatchesOfTeam(int teamId)
        {
            List<MatchInListViewModel> matchesInList = _teamsAndOddsRepository.FindMatchesByTeam(teamId).Select(match => new MatchInListViewModel
            {
                MatchId = match.MatchId,
                StartTime = match.StartTime,
                TeamOneName = match.TeamsAndOddsForMatches.First().Team.Name,
                TeamOneOdds = match.TeamsAndOddsForMatches.First().Odds,
                TeamTwoName = match.TeamsAndOddsForMatches.Last().Team.Name,
                TeamTwoOdds = match.TeamsAndOddsForMatches.Last().Odds,
                DrawOdds = (match.TeamsAndOddsForMatches.First().Odds
                            + match.TeamsAndOddsForMatches.Last().Odds) * 0.15
            }).ToList();
            return PartialView("ListMatches", matchesInList);
        }

        private MatchAndTeamViewModel MatchAndTeamViewModel(Match match)
        {
            MatchAndTeamViewModel matchAndTeamVM = new MatchAndTeamViewModel
            {
                Match = match,
                Teams = _teamsAndOddsRepository.FindTeamsByMatch(match.MatchId)
            };
            return matchAndTeamVM;
        }

    }
}

TessierAshpool.WinStreakers.Web/Areas/User/Controllers/TeamController.cs
using System.Linq;
using System.Web.Mvc;
using TessierAshpool.WinStreakers.Business.Entities;
using TessierAshpool.WinStreakers.DataAccess.Repositories.Interfaces;
using TessierAshpool.WinStreakers.Web.Areas.User.ViewModels;

// <author>Jonas Benzon Illum</author>

namespace TessierAshpool.WinStreakers.Web.Areas.User.Controllers
{
    public class TeamController : Controller
    {

        private ITeamRepository _teamRepository;

        public TeamController(ITeamRepository teamRepository)
        {
            _teamRepository = teamRepository;
        }

        public ViewResult ShowTeam(int id = 1)
        {
            Team currentTeam = _teamRepository.FindById(id);

            return View(new ShowTeamViewModel
            {
                TeamName = currentTeam.Name,
                Members = currentTeam.Members,
                ActiveInGames = currentTeam.TeamsAndOddsForMatches
                                          .Where(team => team.TeamId == id)
                                          .Select(match => match.Match.Game)
                                          .ToArray()
            });
        }

    }
}

TessierAshpool.WinStreakers.Web/Areas/User/Views/Match/ListMatches.cshtml
<!--author: Jonas Benzon Illum -->

@using TessierAshpool.WinStreakers.Web.Areas.User.ViewModels
@model IEnumerable<MatchInListViewModel>

@{
    ViewBag.Title = "ListMatches";
}

<table class="table">
    <thead>
        <tr id="matchTableHeader">
            <td class="col-xs-1 text-center">Tid</td>
            <td class="col-xs-8">Kamp</td>
            <td class="col-xs-1 text-center">1</td>
            <td class="col-xs-1 text-center">X</td>
            <td class="col-xs-1 text-center">2</td>
        </tr>
    </thead>
    <tbody>
        @{
            DateTime currentTime = Model.First().StartTime;
        }

        @Html.Partial("_DateDividerPartial", currentTime)
        @foreach (MatchInListViewModel matchVM in Model)
        {
            if (matchVM.StartTime.Date > currentTime.Date)
            {
                currentTime = matchVM.StartTime;
                @Html.Partial("_DateDividerPartial", currentTime)
            }
            @Html.Partial("_MatchInListPartial", matchVM)
        }
    </tbody>
</table>

TessierAshpool.WinStreakers.Web/Areas/User/Views/Match/ShowMatch.cshtml
@model TessierAshpool.WinStreakers.Web.Areas.User.ViewModels.MatchAndTeamViewModel

<!--author: Jonas Benzon Illum -->

@{
    ViewBag.Title = "Match - " + @Model.Match.Game;
}

<h2>Match:</h2>

<div>
    <h3>@Html.ActionLink(Model.Match.Game.Name, "ShowGame", "Game", new { id = Model.Match.GameId }, null)</h3>
    @Html.Partial("_MatchInfo")
</div>

TessierAshpool.WinStreakers.Web/Areas/User/Views/Match/_DateDividerPartial.cshtml
<!--author: Jonas Benzon Illum -->

@model DateTime

<tr>
    <td class="dateDivider" colspan="5">
        @Model.ToString("dddd, d. MMMM yyyy")
    </td>
</tr>

TessierAshpool.WinStreakers.Web/Areas/User/Views/Match/_MatchInListPartial.cshtml
<!--author: Jonas Benzon Illum -->

@model TessierAshpool.WinStreakers.Web.Areas.User.ViewModels.MatchInListViewModel

<tr id="@Model.MatchId" class="matchRow">
    <td class="text-center alignToMiddle">
        @Model.StartTime.ToString("HH:mm")
    </td>
    <td class="alignToMiddle">
        <span>@(Model.TeamOneName + " vs. " + Model.TeamTwoName)</span>
    </td>
    <td>
        <button type="button" class="btn btn-default btn-sm">@Model.TeamOneOdds.ToString("#0.00")</button>
    </td>
    <td>
        <button type="button" class="btn btn-default btn-sm">@Model.DrawOdds.ToString("#0.00")</button>
    </td>
    <td>
        <button type="button" class="btn btn-default btn-sm">@Model.TeamTwoOdds.ToString("#0.00")</button>
    </td>
</tr>

<script type="text/javascript">
    $('#@(Model.MatchId).matchRow')
        .click({id: @Model.MatchId, controllerAction: "ShowMatch", receivingContainer:'#selectedMatch'}, updateMatchContent);
</script>

TessierAshpool.WinStreakers.Web/Areas/User/Views/Match/_MatchInfo.cshtml
<!--author: Jonas Benzon Illum -->

@model TessierAshpool.WinStreakers.Web.Areas.User.ViewModels.MatchAndTeamViewModel

<p>
    @Html.ActionLink(@Model.Teams.First().Name, "ShowTeam", "Team", null, new { id = Model.Teams.First().TeamId })
    <span>vs.</span>
    @Html.ActionLink(@Model.Teams.Last().Name, "ShowTeam", "Team", null, new { id = Model.Teams.Last().TeamId })
    <br/>
    Match Info: @Html.DisplayFor(matchInfo => Model.Match.Description) <br />
    Starttid: @Html.DisplayFor(matchInfo => Model.Match.StartTime)
</p>